baseURL = 'https://www.bawue.net/'
languageCode = 'de-DE'
title = 'bawue.net'
theme = "ananke"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
contentDir = "content"

[languages]
    [languages.de]
    weight = 1

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/bn-favicon-32x32.png"
  site_logo = "images/bawue-logo.svg"
  description = "Baden-Württembers nichtkommerzieller Internet Provider"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-moon-gray"
  featured_image = "/images/dimension-hero.jpg"
  recent_posts_number = 2
  custom_css = ["assets/ananke/css/custom.css"]
